<h4 style="margin-left: 5px">Menu</h4>
<?php //echo $this->navigation()->menu()->setUlClass('nav nav-list') ?>
<ul class="nav nav-list">
<?php
$class = '';
foreach ($menu as $item) {
    if (isset($routeMatch['alias'])) {
        $class = $routeMatch['alias']  == $item->alias ? ' class="active"' : '';
    }
    $router = isset($item['router']) ? $item['router'] : 'default';
    $params = isset($item['params']) ? $item['params'] : array();
    $url = $this->url($router, $params);
    echo "<li$class><a href=\"$url\">".$this->escape($item['title'])."</a></li>";
}
?>
  <li><?php echo $this->url('libra-article') ?></li>
  <li><?php echo $this->_('CONTACTS_INFO') ?></li>
</ul>